version: '3'
volumes:
  mongo_data:

services:
  mongo:
    image: mongo:focal
    command: ["--keyFile", "/repl-keyfile", "--replSet", "rs"]
    ports:
      - "27016:27017"
    volumes:
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./repl-keyfile:/repl-keyfile
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: widgets
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: "mypassword"
